return table.freeze({
    ["Ambient"] = Color3.fromRGB(90, 86, 77),
    ["Brightness"] = 4,
    ["ColorShift_Bottom"] = Color3.fromRGB(0, 0, 0),
    ["ColorShift_Top"] = Color3.fromRGB(0, 0, 0),
    ["EnvironmentDiffuseScale"] = 1,
    ["EnvironmentSpecularScale"] = 1,
    ["GlobalShadows"] = true,
    ["OutdoorAmbient"] = Color3.fromRGB(129, 118, 72),
    ["ShadowSoftness"] = 0.2,
    ["ClockTime"] = 9.8,
    ["GeographicLatitude"] = 7,
    ["ExposureCompensation"] = 0
})