return table.freeze({
    ["Head"] = 400,
    ["UpperTorso"] = 1000,
    ["LowerTorso"] = 1000,
    ["LeftUpperArm"] = 50,
    ["LeftLowerArm"] = 100,
    ["LeftHand"] = 1000,
    ["RightUpperArm"] = 50,
    ["RightLowerArm"] = 100,
    ["RightHand"] = 1000,
    ["LeftUpperLeg"] = 200,
    ["LeftLowerLeg"] = 100,
    ["LeftFoot"] = 50,
    ["RightUpperLeg"] = 200,
    ["RightLowerLeg"] = 100,
    ["RightFoot"] = 50
})